[workspace]
members = [
    "esc",
    "invensense-mpu",
    "motion-sensor",
    "mpu9250-regs",
]

# Don't optimize build dependencies, like proc macros.
# Helps with build times.
[profile.release.build-override]
opt-level = 0
