# Smoke tests on the tasks.py script

name: Tasks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  demos:
    runs-on: ubuntu-latest
    steps:
      - name: Install build dependencies
        run: sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: thumbv7em-none-eabihf
            override: true
      - name: Run task for pwm-control demo
        run: ./task.py --verbose demo pwm-control --skip-flash
      - name: Run task for pwm-control demo ('demo-' prefix)
        run: ./task.py --verbose demo demo-pwm-control --skip-flash

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Install formatter
        run: |
          python -m pip install --upgrade pip
          pip install black
      - uses: actions/checkout@v2
      - name: Check formatting of tasks.py
        run: black --check tasks.py