# Smoke tests on the tasks.py script

name: Task testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  demos:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          target: thumbv7em-none-eabihf
          override: true
          components: llvm-tools-preview
    - uses: actions-rs/install@v0.1
      with:
        crate: cargo-binutils
        version: latest
        use-tool-cache: true
    - name: Run task for pwm-control demo
      run: ./task.py --verbose demo pwm-control --skip-flash

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    # See https://github.com/psf/black/issues/1654 for why we're
    # locking black version.
    - name: Install formatter
      run: |
        python -m pip install --upgrade pip
        pip install black==19.10b0
    - uses: actions/checkout@v2
    - name: Check formatting of tasks.py
      run: black --check task.py
