# Quality checks that can happen across the whole workspace

name: Workspace

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
jobs:

  # Run clippy, which builds and lints the code
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        target: thumbv7em-none-eabihf
        override: true
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose --target thumbv7em-none-eabihf --workspace --exclude pymotion-sensor -- -D warnings
        name: Run clippy for firmware
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose --workspace --exclude demos-teensy4 -- -D warnings
        name: Run clippy for host

  # Ensure code is formatted
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Check Rust code formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --verbose --all -- --check

  # Run unit, integration, documentation tests for common code
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests in common
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --workspace --exclude demos-teensy4 --exclude pymotion-sensor

  # Build all Rust code on macOS, Ubuntu, and Windows
  xplat:
    strategy:
      matrix:
        host: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.host }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: thumbv7em-none-eabihf
    - name: Build firmware
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --workspace --target thumbv7em-none-eabihf --exclude pymotion-sensor
    - name: Build host
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose --workspace --exclude demos-teensy4
